detection_node:
  ros__parameters:
    pointcloud_topic: "/dev/lidar/points"
    pointcloud_qos_reliability: "best_effort"
    model_config_path: "cfgs/kriso_models/voxelnext04_kriso.yaml"
    ckpt_path: "cfgs/ckpt/voxelnext04_epoch_160.pth"
    score_threshold: 0.3
    output_topic: "/detection/objects"