services:
  lidar_perception:
    build:
      context: .
      dockerfile: Dockerfile
    image: musv_lidar
    container_name: musv_lidar
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
