# KF parameters
state_func_covariance: 10
measure_func_covariance: 0.1
prediction_score_decay: 0.02
LiDAR_scanning_frequency: 10

# max prediction number of state function
max_prediction_num: 12
max_prediction_num_for_new_object: 4

# matching distance threshold
distance_threshold: 10.0

# detection score threshold
input_score: 0
init_score: 0.3
update_score: 0.3
